[package]
name = "tokenizers-python"
version = "0.8.1-rc1"
authors = ["Anthony MOI <m.anthony.moi@gmail.com>"]
edition = "2018"

[lib]
name = "tokenizers"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.3"
typetag = "0.1"
serde_json = "1.0"
serde = "1.0"
libc = "0.2"

[dependencies.pyo3]
version = "0.10"
features = ["extension-module"]

[dependencies.tokenizers]
version = "*"
path = "../../tokenizers"

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
